using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemySpawner : MonoBehaviour
{

    public WaveController waveController;
    public List<GameObject> availableEnemies;
    public List<GameObject> enemiesToSpawn;
    public int direction;
    public bool doSpawnEnemies = false;

    // Fill spawner with enemies generated by our wave controller
    public void FillSpawner(List<GameObject> enemies)
    {
        enemiesToSpawn = enemies;
    }

    public void StartWave(int spawnDelay)
    {
        doSpawnEnemies = true;
        StartCoroutine(SpawnEnemies(spawnDelay));   
    }

    // Routine to spawn our enemies with a delay between spawns
    private IEnumerator SpawnEnemies(int spawnDelay)
    {
        while(doSpawnEnemies)
        {
            if(enemiesToSpawn.Count != 0)
            {
                GameObject newEnemy = Instantiate(enemiesToSpawn[0], transform.position, Quaternion.identity);
                newEnemy.GetComponent<Enemy>().parentSpawner = gameObject;
                newEnemy.GetComponent<Enemy>().StartMovement(direction);
                enemiesToSpawn.RemoveAt(0);
            }
            yield return new WaitForSeconds(spawnDelay);
        }
    }

    // Respawns an enemy if they were not killed by the player
    public void RespawnEnemy(GameObject enemyToRespawn)
    {
        enemiesToSpawn.Add(waveController.availableEnemies[enemyToRespawn.GetComponent<Enemy>().index]);
    }

}
